### ISSUE TITLE
Cannot update existing payment plans

### ISSUE THREAD

**Issue by ipokkel** [strangerstudios/pmpro-payment-plans#66]
**Describe the bug**
Once a payment plan is created and saved successfully it cannot be updated.

**To Reproduce**
1. Go to Memberships > Settings > Levels to create and save a new level.
2. Create a payment plan, set initial payment, and do not check Recurring Payment, save level settings.
3. Open level to edit payment plan, check Recurring payments option, set recurring price and cycle, save level.
4. Open level settings to observe payment plan was not updated with the recurring payment settings.

**Expected behavior**
To be able to change a payment plan's settings after it was created.

**Isolating the problem (mark completed items with an [x]):**
- [x] This bug happens with a default WordPress theme active, or [Memberlite](https://wordpress.org/themes/memberlite/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
Paid Memberships Pro v2.12.3, <br />
Payment Plans Add On v0.4
</details>

**Comment by kimcoleman** [comment]
I cannot recreate this issue. It appears to be resolved. I'm going to close this but we can reopen if this is still happening for sites.
